export const CART_ACTION_TYPES = {
  SET_OPENED: "SET_OPENED",
  ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART",
  INCREASE_QUANTITY: "INCREASE_QUANTITY",
  DECREASE_QUANTITY: "DECREASE_QUANTITY",
  REMOVE_ITEM: "REMOVE_ITEM",
};
